### ISSUE TITLE
Dependency error on `@oclif/errors`

### ISSUE THREAD

**Issue by smacgaha** [percy/percy-agent#154]
When running `percy` from the runtime (not globally), an error is raised:

`Error: Cannot find module '@oclif/errors'`

I believe that this is because `@oclif/errors` is required in the binary, but is only installed as a devDependency.

No idea why this works when installed globally. I suspect it's related to the fact that `@oclif/errors` is also installed as a dependency of `@oclif/command`.

**Comment by djones** [comment]
I think we can remove it completely since, as you point out, it is already a dependency of `@oclif/command`. Also I note that the latest Oclif example project [doesn't list it explicitly](https://github.com/oclif/example-multi-ts/blob/master/package.json#L10) as a dependency.

**Comment by smacgaha** [comment]
Sure thing, I'll try that out
