### ISSUE TITLE
CSSOM serialisation issue

### ISSUE THREAD

**Issue by blake-newman** [percy/percy-agent#188]
Sorry for this vague issue report however I'm not experienced on the purpose of CSSOM serialising. However, during #167 i have noticed an issue with CSSOM serialisation causing multiple snapshots on a page to slow by 2x sequentially per test due to the serialising. 

When running a tests the in the PR it is now much more evident because there is lots more tests ran. 

For each test this [css](https://github.com/percy/percy-agent/blob/master/test/percy-agent-client/test.html#L35) get duplicated. 

`.cls-1 { fill: rgb(141, 123, 216); }` becomes `.cls-1 { fill: rgb(141, 123, 216); }.cls-1 { fill: rgb(141, 123, 216); }` .... and so forth. By the 16th test this is repeated 65536 times.

I assume this may affect actual test speeds, as per snapshot would cause the same thus why raising as an issue. 
 
I can provide more details if needed.

**Comment by Robdel12** [comment]
Hey Blake! Yea this is something we’re actively working on at the moment (though I’m on vacation right now). 

Thanks for the report on this, I’ll make sure this makes it into the refactoring that’s taking place

**Comment by blake-newman** [comment]
Thanks for the response, this was mainly to make sure you were aware of the issue.

Enjoy your vacation! 🏖️
