### ISSUE TITLE
Images with data urls aren't sent, breaking highcharts-boost

### ISSUE THREAD

**Issue by callumacrae** [percy/percy-agent#248]
Hey!

I'm trying to take a snapshot of this page:

![image](https://user-images.githubusercontent.com/472830/59419302-866d6980-8dc2-11e9-999c-e5fa932c458a.png)

This is what I end up with in percy:

![image](https://user-images.githubusercontent.com/472830/59419320-97b67600-8dc2-11e9-93c8-1e35262df844.png)

Clicking back to where the snapshot was taken in Cypress shows the points, they're just somehow lost on the way to Percy.

It works with smaller charts—they use SVG shapes—but with larger charts [Boost](https://www.highcharts.com/docs/advanced-chart-features/boost-module) kicks in and turns the entire thing into a base 64 image.

In the markup, it looks like this:

![image](https://user-images.githubusercontent.com/472830/59419470-eb28c400-8dc2-11e9-8fe8-cfbe4c394893.png)

Is Percy stripping it out? Is this a bug (I seem to recall percy strips out third party assets - possible side effect of that?), or is there a way I can tell Percy not to do this?

Thanks!

**Comment by Robdel12** [comment]
Hey Callum,

That's interesting. Could you upgrade to the latest `@percy/agent`? It looks like you're currently on `0.4.7` & the latest is `0.7.0`. I ask because v0.5.2 carries a big refactor for how we handle cloning the DOM (#208 )& it would be good to get to at least that version.

**Comment by callumacrae** [comment]
uhhh that wasn't supposed to close! turns out you can close an issue by saying "Might fix percy/percy-agent#248." in a pull request in a private repo 😂 

Updating hasn't fixed the issue :(

**Comment by callumacrae** [comment]
I'm not sure what changed, but I just had a build where it worked fine. I'll close this and reopen if it reoccurs :)

thanks!
