### ISSUE TITLE
Feature request: output list of ignored files when running percy snapshot with -i option

### ISSUE THREAD

**Issue by abahgat** [percy/percy-agent#296]
I am running percy via CLI to test my own website.
I have a large number of pages that look the same and I am looking to ignore a subset of them via passing globs to `-i`.
I would find it extremely useful if the command would output a list of resources that it is ignoring because of the glob I happen to have passed. Would it make sense to add that?

Also, having the option to dry run `percy snapshot` would go a long way ;)

**Comment by jm3** [comment]
Yes, same! I just ran into this when trying to get a comma-separated list of globs working, until I realized that I can't include a space between the globs — doh! :)

#nospaces

[![asciicast](https://asciinema.org/a/RCB12C2YzXu8lG5OoMQZ1Djzh.svg)](https://asciinema.org/a/RCB12C2YzXu8lG5OoMQZ1Djzh)

**Comment by Robdel12** [comment]
With the last agent based SDK migrated to CLI, you can check the migration doc to see how you can upgrade: https://docs.percy.io/docs/migrating-to-percy-cli#completed

The CLI has a more robust `snapshot` command: https://docs.percy.io/docs/percy-snapshot
