### ISSUE TITLE
`percy start --detached` should clean up the PID file

### ISSUE THREAD

**Issue by Robdel12** [percy/percy-agent#340]
## What is this?

When running agents server in a detached state we write the PID to a file but we don't clean that file up after stopping Percy. This can cause a lot of issues since Percy looks for a PID file before starting. 

We should delete that file with the PID after the agent server successfully stops

From @wwilsman:

> since start is responsible for creating that pid via the process service, and also does build cleanup on termination, we should add pid cleanup as part of that termination. DRYing up those signal handlers should also prevent multiple console outputs like I did with the exec command.

> Cleaning the file should probably go here: https://github.com/percy/percy-agent/blob/master/src/services/process-service.ts

> And then calling the process cleanup should happen in these handlers: https://github.com/percy/percy-agent/blob/master/src/commands/start.ts#L59-L72

**Comment by wwilsman** [comment]
#382 Will hopefully solve this. If it continues to persist, maybe something else is happening when the server receives the stop request that makes it not clean the file up in time before the process is killed.

**Comment by Robdel12** [comment]
This isn't an issue in `@percy/cli`. With the last agent based SDK migrated to CLI, you can check the migration doc to see how you can upgrade: https://docs.percy.io/docs/migrating-to-percy-cli#completed
