### ISSUE TITLE
[Orb Enhancement] Convert `percy_token` env var type to `env_var_name`

### ISSUE THREAD

**Issue by KyleTryon** [percy/percy-agent#357]
https://github.com/percy/percy-agent/blob/master/.circleci/orb.yml#L30

Utilize more secure parameter type `env_var_name` for environment variables.
https://circleci.com/docs/2.0/orbs-best-practices/#parameters

```
_Consider adding the `orbtoberfest` label on this issue to make this issue eligible for #Orbtoberfest https://circleci-public.github.io/hacktoberfest_
```

**Comment by Shin-027** [comment]
Hi, I would like to pick this up.

**Comment by KyleTryon** [comment]
#366 merged.
