### ISSUE TITLE
[Orb Enhancement] Detail usecase.

### ISSUE THREAD

**Issue by KyleTryon** [percy/percy-agent#358]
Provide a more detailed description of the function of this orb:
https://github.com/percy/percy-agent/blob/master/.circleci/orb.yml#L2

Explain to new users the significance of when to run "finalize"

_Consider adding the `orbtoberfest` label on this issue to make this issue eligible for #Orbtoberfest https://circleci-public.github.io/hacktoberfest_

**Comment by sccalabr** [comment]
https://github.com/percy/percy-agent/pull/367/files

**Comment by Robdel12** [comment]
Closed with https://github.com/percy/percy-agent/pull/367

Thanks for the PR! 😃
