### ISSUE TITLE
[Orb Enhancement] Add missing job description.

### ISSUE THREAD

**Issue by KyleTryon** [percy/percy-agent#359]
The `finalize_all` job currently contains no description.

https://github.com/percy/percy-agent/blob/master/.circleci/orb.yml#L36

_Consider adding the `orbtoberfest` label on this issue to make this issue eligible for #Orbtoberfest https://circleci-public.github.io/hacktoberfest_

**Comment by sccalabr** [comment]
Create pull request https://github.com/percy/percy-agent/pull/365. Let me know if I did anything wrong.
