### ISSUE TITLE
Add the ability to suppress log output entirely

### ISSUE THREAD

**Issue by Robdel12** [percy/percy-agent#361]
## What is this?

It would be nice to suppress Percy log output entirely. In theory, this shouldn't be too hard. We would probably want to add a new config option (flag, `.percy.yml`, & an env var) to disable logging. Seems like we'll just need to pass `silent: true` to the logger(s) when that config option is present.

cc: @wwilsman since you recently upgraded us to winston 3.

**Comment by wwilsman** [comment]
For anyone coming across this, you can currently silence logs by passing an unrecognized log level.

`LOG_LEVEL=silent` & `LOG_LEVEL=foo` will both silence agent logging.

**Comment by Robdel12** [comment]
With the last agent based SDK migrated to CLI, you can check the migration doc to see how you can upgrade: https://docs.percy.io/docs/migrating-to-percy-cli#completed
