### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by koolay** [percy/percy-agent#390]
failed to run `PERCY_TOKEN=xxxx percy exec -- cypress run --record`.

```
[percy] created build #19: https://percy.io/xxx/builds/2747798 Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
```

**Comment by Robdel12** [comment]
Hi there! Looks like you need to run `npm install` or `yarn install` in your project. If that doesn't work, I would remove the node_modules folder and reinstall again.

When the dependencies were installed, Puppeteer didn't install Chrome correctly.

**Comment by koolay** [comment]
I see now.  There was  no file in the folder: `/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/.local-chromium/mac-686378/`.
