### ISSUE TITLE
`MaxListenersExceededWarning` when running `npx percy start`

### ISSUE THREAD

**Issue by danielrozenberg** [percy/percy-agent#402]
We just started using the `@percy/agent` to upload our test suites (after being on `@percy/puppeteer` v0.4.0 for much longer than we care to admit) and our Travis logs are showing the `MaxListenersExceededWarning` errors: https://travis-ci.org/ampproject/amphtml/jobs/601418082#L2197-L2204

I managed to isolate this to the Percy agent command locally so this isn't an issue with our own tests (surprisingly enough!)

**Comment by Robdel12** [comment]
Hey Daniel! Thanks for opening the issue & linking to the build (& PR). I wanted to drop a note that we've been taking a look at what's going on 👀

**Comment by djones** [comment]
Possibly related: https://github.com/percy/percy-agent/pull/189

**Comment by Robdel12** [comment]
Coming back to this -- I think this is related to this issue: https://github.com/winstonjs/winston/issues/1334#issuecomment-392388321
 
I don't think this is a memory leak, but want to keep digging

**Comment by Robdel12** [comment]
Closed with #407 

Thanks for reporting! This is a good one to track down

**Comment by danielrozenberg** [comment]
Confirming this is now working on our end. Thanks for the quick fix!
