### ISSUE TITLE
failure to capture snapshots

### ISSUE THREAD

**Issue by travi** [percy/percy-agent#415]
i've been seeing a problem with recent build that results in failure to capture and report snapshots, which gives the following error: `Failed to inject agent JS: Error: Evaluation failed: TypeError: Cannot read property 'length' of undefined`

[our command](https://github.com/dsmjs/site/blob/master/package.json#L25) is simply `npx percy snapshot public/`, which we are running as an [`after_success` step](https://github.com/dsmjs/site/blob/41fcfd075537551112999955507ae03a816e9300/.travis.yml#L11)

[travis-ci output](https://travis-ci.org/dsmjs/site/jobs/607301985#L345-L389)

it doesn't seem like we are doing anything fancy or outside of what is recommended and i don't think we've changed anything since the time this was working, so i could use some help understanding if this is unique to us or something more broad.

**Comment by Robdel12** [comment]
Hey @travi! Looks like I shipped a bug #406 -- #418 should fix this 👍 I'm not going to close this since I _think_ that's the cause of that issue

**Comment by travi** [comment]
thanks for digging in. ill keep an eye on upcoming builds and report back

**Comment by Robdel12** [comment]
Looks like things are going smoothly [here](https://travis-ci.org/dsmjs/site). Going to close :)

**Comment by travi** [comment]
indeed. sorry that i havent gotten a chance to follow up, but thanks so much for the quick resolution :)

**Comment by Robdel12** [comment]
No problem! Happy it was cleaned up 😃
