### ISSUE TITLE
`isCSSOM` failing on a stylesheet

### ISSUE THREAD

**Issue by slin12** [percy/percy-agent#416]
Hi, we're running percy with cypress and while taking a snapshot of a page I'm getting this error:

<img width="802" alt="Screen Shot 2019-11-04 at 5 24 04 PM" src="https://user-images.githubusercontent.com/30914906/68163162-ea3a2f80-ff27-11e9-82ec-2dc71565f5d8.png">

I tracked it down to one stylesheet, who's ownerNode returns:

```
<style>
      @keyframes VOLUME_SMALL_WAVE_FLASH {
          0% { opacity: 0; }
         33% { opacity: 1; }
         66% { opacity: 1; }
        100% { opacity: 0; }
      }

      @keyframes VOLUME_LARGE_WAVE_FLASH {
          0% { opacity: 0; }
         33% { opacity: 1; }
         66% { opacity: 1; }
        100% { opacity: 0; }
      }

      .volume__small-wave {
        animation: VOLUME_SMALL_WAVE_FLASH 2s infinite;
        opacity: 0;
      }

      .volume__large-wave {
        animation: VOLUME_LARGE_WAVE_FLASH 2s infinite .3s;
        opacity: 0;
      }
  </style>
```

`ownerNode.innerText && ownerNode.innerText.trim()` is returning undefined, causing the snapshot to fail. 

The stylesheet is not loaded in from us directly, it comes from some external javascript. Any ideas on how to fix this and/or if this is intended behavior?

**Comment by Robdel12** [comment]
Hey @slin12, thanks for opening this issue! That's interesting that `ownerNode.innerText && ownerNode.innerText.trim()` returns `undefined`. 

Are you sure that's the stylesheet that's causing the issue? I'm trying to replicate this behavior locally (for tests) and for that specific style tag, doesn't fail. Even setting the innerText to `undefined` will result in a string "undefined":

<img width="424" alt="image" src="https://user-images.githubusercontent.com/2072894/68165403-f4a6fa00-ff24-11e9-82fd-05784ac41607.png">

I'm sure there's a bug here, but I'm having a hard time replicating it. Once we can replicate it, I _believe_ this should fix it: 

```js
const hasStyleInDom = !!ownerNodeInnerContent && ownerNodeInnerContent.length > 0
```

**Comment by slin12** [comment]
Thanks for the quick response! Let me know if this is helpful, otherwise I can poke around some more to get steps to reproduce:

![Screen Shot 2019-11-04 at 6 17 36 PM](https://user-images.githubusercontent.com/30914906/68166144-700da900-ff2f-11e9-87bb-cbf5da60a4f1.png)

**Comment by slin12** [comment]
here's a fiddle w/ the offending element: https://jsfiddle.net/nbpqaz97/1/

**Comment by Robdel12** [comment]
Thank you so much for that, that explains it! For some reason, the browser does cannot return `innerText` for that content. But it does for `innerHTML` 🤔 

I'll have a PR and fix out soon
