### ISSUE TITLE
Error when upgrading

### ISSUE THREAD

**Issue by bradleypriest** [percy/percy-agent#417]
When upgrading `@percy/agent` from 0.19.1 to 0.19.6 we're seeing 6 of our snapshots failing to be processed with the following error:

```
[percy] Snapshotting failed. Note that Poltergeist and Rake::Test are no longer supported by percy-capybara. Error: unknown error: Cannot read property 'length' of undefined
```

Any ideas what could cause this?

**Comment by Robdel12** [comment]
Hey @bradleypriest! Looks like I shipped a bug #406 -- #418 should fix this 👍
