### ISSUE TITLE
TypeErrors when running percy exec with PERCY_TOKEN present

### ISSUE THREAD

**Issue by jfuston** [percy/percy-agent#485]
Hey all, seeing a couple errors upon initial runs that I've not seen in our other projects, wanted to check and see if you could point me in the right direction.

I'm running `percy exec -- cypress run --env configFile=${env} --browser chrome --spec 'cypress/tests/visual/*'` and in the console I get the following but _only_ when the PERCY_TOKEN is present.
```
[percy] TypeError Cannot read property 'body' of undefined | Fri Mar 13 2020 16:10:37 GMT-0500 (Central Daylight Time)
[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.
[percy] percy has started.
Possibly unhandled TypeError: A catch filter must be an error constructor
    at Promise$catch (/Users/jfuston/dev/response/node_modules/bluebird/js/bluebird.js:964:21)
    at try_once (/Users/jfuston/dev/response/node_modules/bluebird-retry/lib/bluebird-retry.js:81:14)
    at retry (/Users/jfuston/dev/response/node_modules/bluebird-retry/lib/bluebird-retry.js:123:12)
    at PercyClient._httpPost (/Users/jfuston/dev/response/node_modules/percy-client/dist/main.js:141:14)
    at PercyClient.createBuild (/Users/jfuston/dev/response/node_modules/percy-client/dist/main.js:198:19)
    at BuildService.create (/Users/jfuston/dev/response/node_modules/@percy/agent/dist/services/build-service.js:16:18)
    at AgentService.start (/Users/jfuston/dev/response/node_modules/@percy/agent/dist/services/agent-service.js:34:48)
    at Exec.start (/Users/jfuston/dev/response/node_modules/@percy/agent/dist/commands/percy-command.js:36:37)
    at Exec.run (/Users/jfuston/dev/response/node_modules/@percy/agent/dist/commands/exec.js:25:24)
^C[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.
```
The tests will run as expected if I don't interrupt the process but it still collects 0 snapshots at the end.

I'm on `"@percy/cypress": "2.3.1",` and `"cypress": "4.1.0",` but have tried down to `"@percy/cypress": "2.0.0"` and `"cypress": "4.0.0"` and still see the same issue.

Any ideas?

**Comment by Robdel12** [comment]
Can you tell me which versions of `bluebird-retry` & `bluebird` your project is resolving to? (`yarn why` or `npm ls`)

**Comment by jfuston** [comment]
here's the output for those two:
```
jfuston-MacBook-Pro:response jfuston$ npm ls bluebird-retry
response@0.3.0 /Users/jfuston/dev/response
└─┬ @percy/cypress@2.3.1
  └─┬ @percy/agent@0.24.3
    └─┬ percy-client@3.6.1
      └── bluebird-retry@0.11.0

jfuston-MacBook-Pro:response jfuston$ npm ls bluebird
response@0.3.0 /Users/jfuston/dev/response
├─┬ @percy/cypress@2.3.1
│ └─┬ @percy/agent@0.24.3
│   └─┬ percy-client@3.6.1
│     └── UNMET PEER DEPENDENCY bluebird@3.7.2
├─┬ babel-eslint@4.1.8
│ └─┬ babel-core@5.8.38
│   └── bluebird@2.11.0
├── bluebird@0.8.1-0
├─┬ UNMET PEER DEPENDENCY cypress@4.1.0
│ └── bluebird@3.7.2
└─┬ grunt-emma@2.2.1 (github:emmadev/grunt-emma#d923ea54e5ed5bbeb86bc7440a4d76884d3ca58f)
  └─┬ request-promise@4.2.5
    └── bluebird@3.7.2
```

**Comment by jfuston** [comment]
Updating that devDependency to `bluebird@3.7.2` fixed it. I must've overlooked the output complaining about that when initially installing `@percy/cypress`. Thank you for digging through that so quickly!

**Comment by Robdel12** [comment]
No problem! The hero here is behind the scenes, @wwilsman. He spotted that and realized the error message here was different from their wiki: https://github.com/petkaantonov/bluebird/wiki/Error:-Catch-filter-must-inherit-from-Error-or-be-a-simple-predicate-function

Whoop! That's good that it's working now 😃

**Comment by Robdel12** [comment]
FWIW, we're going to be getting rid of bluebird in the near future & use native node promises. Hopefully this is no ever a possible issue soon 🤞

**Comment by jfuston** [comment]
Glad to hear it, I'll keep an eye out for that change! Thanks again for the insane responsiveness.

**Comment by Robdel12** [comment]
No problem, glad we could get it sorted 😃
