### ISSUE TITLE
feature: speed up snapshot taking -> parallel processing?

### ISSUE THREAD

**Issue by naltatis** [percy/percy-agent#513]
I'd like the `percy snapshot` command to process the html files in parallel or maybe increase the concurrency if this is already happening under the hood. A `percy snapshot` run for ~300 html files takes around 10min in my current project. I've tried to run two instances in parallel but this doesn't work (see #482).

**Comment by Robdel12** [comment]
The new `@percy/cli` snapshot command is much quicker (and will be gaining parallel support here in the near future): https://docs.percy.io/docs/percy-snapshot
