### ISSUE TITLE
chore: note on using puppeteer >= 3 & ouf of memory docs update

### ISSUE THREAD

**Issue by artemgurzhii** [percy/percy-agent#552]
We are using Percy integration with Gitlab and we have problems with it. 

[Here is a bit more detailed explanation of our problem](https://github.com/puppeteer/puppeteer/issues/1321#issuecomment-342883872). 

The solution is to add `'--disable-dev-shm-usage'` to the puppeteer launch args, but I'm not sure that everyone who is using that package will need it. Therefore I'm proposing to delegate those flags to be passed by the user using `.percy.yml` config and use default flags(current flags) unless no flags were passed/defined through the config file. In that way, it will not break any current builds + will have backward compatibility with the previous/future releases

**Comment by artemgurzhii** [comment]
After thinking a bit more, I think it would be a good idea to allow users to have more control over the puppeteer configuration(not only on the flags). Allow user having/passing their own puppeteer launch config & merge default config with the user one.

What are your thoughts?

**Comment by artemgurzhii** [comment]
P.S. Moving to `WIP` for now as with all flags added I still receive `[0820/163249.466981:FATAL:memory.cc(38)] Out of memory. size=262144`(I have configured `dumpio: true` puppeteer flag) with the error `(node:103) UnhandledPromiseRejectionWarning: Error: Page crashed!`

**Comment by Robdel12** [comment]
With the last agent based SDK migrated to CLI, you can check the migration doc to see how you can upgrade: https://docs.percy.io/docs/migrating-to-percy-cli#completed

The new SDK toolchain (`@percy/cli` and friends) no longer uses Puppeteer
