### ISSUE TITLE
Dont hardcode localhost as hostname to the agent

### ISSUE THREAD

**Issue by pscheit** [percy/percy-agent#553]
Hey folks,

thank you so much for writing percy, it's a blast!

So I went deep dive into the whole percy architecture, because I am trying to integrate percy with my selenium testsuite, which runs in behat/php/mink.

So far so good, I have a plan, but one thing, would make my life easier:
https://github.com/percy/percy-agent/blob/45b27ee5dc0905b39449fcdaab82e6ca35c5a175/src/percy-agent-client/percy-agent.ts#L27
If I could pass here another host.

Because when I run the percy agent service on another docker container, I could connect to that diretly, instead of dispatching the domstring myself

**Comment by davidungio** [comment]
I'd like the ability to configure this host as well.

**Comment by wwilsman** [comment]
Hey @pscheit and @davidungio!

This feature will be in the next new CLI tool along with the next major SDK releases. Depending on which SDK you are using, you might be able to opt in to one of the betas now.

Here is an issue on the new CLI repo that tracks which SDKs have betas – https://github.com/percy/cli/issues/57. New install instructions can be found in the respective SDK repo readmes.

In the future (and currently in those betas) you'll be able to [set an environment variable](https://github.com/percy/cli/blob/master/packages/sdk-utils/index.js#L3) where your tests run that tell the SDK where the Percy CLI server is running.

**Comment by Robdel12** [comment]
With the last agent based SDK migrated to CLI, you can check the migration doc to see how you can upgrade: https://docs.percy.io/docs/migrating-to-percy-cli#completed

This is solved in `@percy/cli` if you still need it (`PERCY_SERVER_ADDRESS` is the env var to set it)
