### ISSUE TITLE
Security vulnerability in axios v0.19.0

### ISSUE THREAD

**Issue by FergusMcGlynn** [percy/percy-agent#600]
Axios v0.19.0 has known Server-Side Request Forgery vulnerability. Should upgrade dependency to v0.21.1. See:
- https://github.com/axios/axios/releases/tag/v0.21.1
- https://snyk.io/vuln/SNYK-JS-AXIOS-1038255

**Comment by khitrenovich** [comment]
@Robdel12 This fails `npm audit` due to https://npmjs.com/advisories/1594. Any ETA will be appreciated. Thank you!

**Comment by Robdel12** [comment]
Closed with #593 👍🏼 

Thanks y'all!
