### ISSUE TITLE
Feature request: Link to Pull Request inside Percy Builds and Slack message

### ISSUE THREAD

**Issue by mohsenny** [percy/percy-agent#608]
Hi,
It would be extremely convenient and save a noticeable amount of time if there is a link to the `Pull Request` inside:

- Percy's build
- Integrated Slack message 

Currently, I cannot see such linking:

<img width="703" alt="Screenshot 2021-03-15 at 11 24 44" src="https://user-images.githubusercontent.com/1129811/111139470-7418f480-8581-11eb-8f7a-aba024086e65.png">

<img width="1438" alt="Screenshot 2021-03-15 at 11 24 58" src="https://user-images.githubusercontent.com/1129811/111139478-767b4e80-8581-11eb-8043-0f1e9c753033.png">

I am aware that the other way around "does" exist and there is a link to Percy's build inside the Pull Request already. As a QA who's responsible for following up on failing builds on the integrated Slack channel, this would make my life tremendously easier.

Thank you

**Comment by Robdel12** [comment]
Hey @mohsenny thanks for the issue! This repo is for SDK related things though -- I've passed this info along to the team. You could also (in the future, I've recorded this one :D) reach out to support@percy.io for these types of requests
