### ISSUE TITLE
Please upgrade Puppeteer to latest

### ISSUE THREAD

**Issue by psteininger** [percy/percy-agent#615]
The Puppeteer version in 4 major releases behind. This causes an installation problem on Apple Silicon, because of hard-coded path for chromium and a mismatch in the architecture naming. This has been resolved in here already https://github.com/puppeteer/puppeteer/issues/6622

**Comment by Robdel12** [comment]
Hey @psteininger! This package is about to be deprecated (we have one more SDK to move over to the new CLI before). You can check this doc to see how to upgrade your current SDK away from percy agent: https://docs.percy.io/docs/migrating-to-percy-cli#current-migration-status
