### ISSUE TITLE
Support Chrome in a container

### ISSUE THREAD

**Issue by geoffharcourt** [percy/percy-agent#629]
Hello Percy folks!

We use Alpine Linux for our CI to get a small footprint and run Chrome in a Docker container as a service. This provides some great speed benefits for us as well as makes is easy to swap out Chrome versions (or even test multiple versions) in a single CI run. (We're using Browserless' Docker images to do this.)

Unfortunately, we also love using Percy. This means that our Percy-running containers need to download Chromium and have it present in the main CI container in order to make it available for asset discovery, etc.

Is this a feature/capability that Percy would be open to supporting?

**Comment by Robdel12** [comment]
Hey @geoffharcourt! TL;DR: you can now :D https://docs.percy.io/docs/skipping-puppeteer-chromium-download

The longer answer is Percy Agent is no longer being developed -- all of our SDKs have moved over to a new toolchain built on `@percy/cli`. I would recommend upgrading your SDK to the latest version that uses `@percy/cli`. https://docs.percy.io/docs/migrating-to-percy-cli From there you can also provide your own Chrome binary path to the CLI: https://docs.percy.io/docs/skipping-asset-discovery-browser-download

**Comment by geoffharcourt** [comment]
Hi @Robdel12, thanks for your help here.

I had held off upgrading because [this doc](https://docs.percy.io/docs/migrating-to-percy-cli) said that the Capybara integration was WIP and still hadn't migrated to use CLI over agent, but that seems to be out of date! Making that change now.

I'm going to open a separate ticket on the CLI repo, the specific thing I'm looking to do is to not launch a local version of Chrome/Chromium, but to use one that's not on the local machine but available at another host/port combination.
