### ISSUE TITLE
No data found for resource with given identifier (Possible race condition)

### ISSUE THREAD

**Issue by Robdel12** [percy/percy-agent#92]
## Problem

As of `@percy/agent` version `0.1.15` we introduced responsive width detection, which renders the DOM snapshot we take in the widths that are specified to the SDK _concurrently_. When trying to snapshot some sites, this can cause a race condition where this error is thrown:

```
Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier
    at Promise (/Users/robertdeluca/Projects/Work/percy-agent/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/robertdeluca/Projects/Work/percy-agent/node_modules/puppeteer/lib/Connection.js:185:12)
    at _contentPromise._bodyLoadedPromise.then (/Users/robertdeluca/Projects/Work/percy-agent/node_modules/puppeteer/lib/NetworkManager.js:591:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Googling that error returns a few different issues that might be helpful:

- https://github.com/GoogleChrome/puppeteer/issues/2258
- https://github.com/GoogleChrome/puppeteer/issues/1274
- https://github.com/GoogleChrome/puppeteer/issues/2176

You can recreate this issue repeatedly with this puppeteer script:

```js
const puppeteer = require('puppeteer');
const {percySnapshot} = require('@percy/puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  await page.goto('https://www.nash.io/company/careers');

  await percySnapshot(page, 'Does this snapshot?');
  await browser.close();
})();
```

If you downgrade `@percy/agent` to `v0.1.14` the above snippet captures the snapshot properly. Singling out a width also does not help in the latest version. 

### Where does this blow up in agent? 💥 

Given the above puppeteer script, this error comes up on an `.mp4` video file when calling `.buffer()`on the response: https://github.com/percy/percy-agent/blob/master/src/services/response-service.ts#L70

![image](https://user-images.githubusercontent.com/2072894/54061193-6d528c80-41c5-11e9-9746-ccaa2ba57b83.png)

**Comment by anaulin** [comment]
Digging deeper into what the agent is doing in this case, here is a Puppeteer-only script that reproduces this issue:
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.nash.io/company/careers';


(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on('response', async (response) => {
  if ([200, 201, 304].includes(response.status())) {
    await response.buffer()
  }
});

console.log('waiting for url to load')
await page.goto(URL)

await browser.close()

})();
```

**Comment by anaulin** [comment]
In the repro script above, adding a wait until there are no more network requests fixes the issue, i.e. changing the `page.goto(URL)` call to be:
```javascript
await page.goto(URL, { waitUntil: 'networkidle0' }) 
```

However, adding that same wait to our agent code on line https://github.com/percy/percy-agent/blob/master/src/services/asset-discovery-service.ts#L162 did not help the issue we're seeing, though.

**Comment by anaulin** [comment]
I'm taking back my previous comment -- the repro script fails even with `{ waitUntil: 'networkidle0' }`, it just fails less frequently. :-/

**Comment by anaulin** [comment]
I added my reproduce example to https://github.com/GoogleChrome/puppeteer/issues/1274#issuecomment-471793396, where the OP was having a similar situation involving videos.

**Comment by anaulin** [comment]
I believe this issue can be marked as closed or resolved, if we believe the conclusion in https://github.com/GoogleChrome/puppeteer/issues/1274#issuecomment-473486095 about how the underlying issue is the server intermittently resetting the connection.

Would also be good to confirm/deny that the change in https://github.com/percy/percy-agent/pull/98 made at least things more robust.

**Comment by Robdel12** [comment]
It did from what I can tell! I think this is good to close. 👍 Nice work on this one
